theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/MineralsCloud/EquationsOfState.jl/archive/refs/tags/v4.0.0.zip
  tar_url: https://github.com/MineralsCloud/EquationsOfState.jl/archive/refs/tags/v4.0.0.tar.gz
